---
title: "Paper figures"
author: "Francesco Beghini"
date: "January 6, 2019"
output: 
  html_document: 
    fig_caption: yes
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE, 
  paged.print=FALSE, 
  echo=FALSE, 
  fig.path = 'plots/',
  dev=c('svg', 'png'))
knitr::opts_chunk$set(fig.width=8, fig.height=6) 
library(phyloseq)
library(magrittr)
library(tidyverse)
library(reshape2)
library(ggsignif)
library(DESeq2)

source('R/loadQiimeData.R')
source('R/ggtheme.R')
source('R/calculatePairwiseDistances.R')
```

```{r QIIME data loading, cache=TRUE}
gg_topi <- loadQiimeData()
mappingfile <- data.frame(sample_data(gg_topi))
gg_topi.genus <- tax_glom(gg_topi,taxrank = "Genus")
gg_topi.genus.relab <- transform_sample_counts(gg_topi.genus, function(x) x/sum(x))

gg_topi.family <- tax_glom(gg_topi,taxrank = "Family")
gg_topi.family.relab <- transform_sample_counts(gg_topi.family, function(x) x/sum(x))
```

# Figure 3
```{r Calculate alpha diversity, cache=TRUE}
alpha_div <- estimate_richness(gg_topi) %>% bind_cols(data.frame(sample_data(gg_topi)))
```

```{r, cache=TRUE}
filt_alpha <- alpha_div %>% 
  filter(timepoint %in% c('T1', 'T2', 'T3')) %>%
  select('Description','condizione','timepoint','Observed', 'se.chao1', 'Simpson', 'Shannon') %>%
  rename('se.chao1' = 'Chao1') %>%
  mutate(t=as.numeric(stringr::str_sub(timepoint,2,2))) %>% droplevels()

ttest_res <- data.frame()
for ( ts in combn(levels(filt_alpha$timepoint), 2, simplify = FALSE)){
  for( measure in c('Observed', 'Chao1', 'Simpson', 'Shannon') ){
    ttest_res %<>% bind_rows( data.frame(Measure = measure,
                                         Timepoint1 = ts[1],
                                         Timepoint2 = ts[2],
                                         pvalue = with(filt_alpha %>% filter(timepoint %in% ts), t.test(as.formula(paste(measure, 't', sep = '~'))))$p.value))
  }
}
```

```{r, cache=TRUE}
knitr::kable(ttest_res)
```


```{r fig3a, fig.cap='Fig 3A: Alpha diversity controls T1 vs T2 and pre and post challenge T2 vs T3', fig.height=3, fig.width=2}
annot_df <- (ttest_res %>% filter(Measure == 'Chao1') %>% filter(pvalue < 0.05) %>% mutate(pvalue = paste('p=',signif(pvalue,2), sep = '')))
filt_alpha %>%
  melt(id.vars = c('Description','condizione','timepoint'), measure.vars =  c('Chao1')) %>%
  ggplot(aes(timepoint, value)) +
  geom_boxplot(aes(fill=timepoint), width=0.5, alpha=.8) +
  xlab('Timepoint') +
  ylab('Chao1 Index') +
  scale_fill_manual(name = "Timepoint", values = cm_palette) +
  # ggsignif::geom_signif(comparisons = list(c('T1','T3')), y_position = 240, tip_length = 0, test = 't.test') +
  # ggsignif::geom_signif(comparisons = list(c('T2','T3')), y_position = 230, tip_length = 0, test = 't.test') +
  geom_signif(data = annot_df, manual=TRUE, aes(annotations = pvalue, xmin=Timepoint1, xmax=Timepoint2, y_position = c(235,225))) +
  guides(fill=FALSE) +
  theme_cm()
```

```{r supplfig3a, fig.cap='Fig 3A: Alpha diversity controls T1 vs T2 and pre and post challenge T2 vs T3', fig.dim = c(5,5)}
filt_alpha %>%
  melt(id.vars = c('Description','condizione','timepoint'), measure.vars =  c('Observed', 'Chao1', 'Simpson', 'Shannon')) %>%
  ggplot() +
  geom_boxplot(aes(timepoint, value, fill=timepoint)) +
  scale_fill_manual(name = "Timepoint", values = cm_palette) +
  xlab('Timepoint') +
  ylab('Value') +
  facet_grid(variable~.,scales = 'free_y') +
  guides(fill=FALSE) +
  theme_cm()
```

```{r, cache=TRUE}
distwu <- phyloseq::distance(gg_topi, "wunifrac")
ordwu <-  ordinate(gg_topi, method = "MDS", distance = distwu, weighted = TRUE) %>% plot_ordination(gg_topi, ., justDF = TRUE)
distanceswu <- calculate_pairwise_distances(distwu)
distancesbc <- calculate_pairwise_distances(phyloseq::distance(gg_topi, "bray"))
metadata_2cat <- mappingfile[mappingfile$timepoint %in% c('T2','T3'),]
distwu_2cat <- phyloseq::distance(subset_samples(gg_topi, timepoint %in% c('T2','T3')), "wunifrac")
permanova <- vegan::adonis(formula = distwu_2cat ~ merge_timepoint, data = metadata_2cat)
```

```{r fig3b, fig.cap="Fig 3B: Beta diversity differences pre and post challange T2 vs T3", fig.dim = c(5,3)}
subset(ordwu, timepoint %in% c('T2','T3')) %>%
ggplot(aes(Axis.1, Axis.2)) +
  geom_point(aes(color=timepoint), size=3, alpha=.8) +
  scale_color_manual(name = "Timepoint", values = cm_palette[c(2,3)]) +
  theme_cm() +
  annotation_custom(grob = grid::textGrob(label = bquote(atop("p-value"==.(permanova$aov.tab$`Pr(>F)`[1]),italic(R^2)==.(signif(permanova$aov.tab$R2[1], 2)))),
    gp=grid::gpar(col="black", fontsize=11)),  xmin = 0.15, xmax = .15, ymin = .12, ymax = .12)
```

```{r DESeq2 loading, cache=TRUE}
pds_genus <- phyloseq_to_deseq2(gg_topi.genus, design = ~timepoint)
dds_genus <- DESeq2::DESeq(pds_genus, parallel = TRUE, quiet = TRUE)
```

```{r DESeq2 T2 T3, cache=TRUE}
res_genus <- DESeq2::results(dds_genus, contrast = c('timepoint', 'T2','T3'), alpha = 0.05)
res.filt_genus <- res_genus[!is.na(res_genus$padj),]
res.filt_genus <- res.filt_genus[res.filt_genus$padj<0.05,]

t23_samples_idx_genus <- grep('T2|T3', sample_names(gg_topi.genus.relab), perl = TRUE)

genus_ab_t <- otu_table(gg_topi.genus.relab)[rownames(res.filt_genus), t23_samples_idx_genus] %>%
            data.frame %>%
            tibble::rownames_to_column("OTU") %>%
            tidyr::gather_("SampleID", "Abundance", setdiff(colnames(.), "OTU")) %>%
            mutate(timepoint=factor(stringr::str_sub(.$SampleID,12, 13)))
```

```{r, cache=TRUE}
lacno_bact_relabs <- genus_ab_t %>% 
                     bind_cols(data.frame(tax_table(gg_topi.genus.relab)[genus_ab_t$OTU,c('Phylum','Family','Genus')])) %>% 
                     filter(Family %in% c('Bacteroidales S24-7 group') | Genus %in% c('Lachnospiraceae NK4A136 group')) %>% 
                     mutate(taxlab = str_replace(ifelse(stringr::str_detect(Genus,'uncultured'), paste(Family,sep = ''), paste(Genus, sep = '')), ' group','')) %>%
                     select(taxlab, Abundance, timepoint, OTU)

lacno_bact_relabs %>% group_by(timepoint,taxlab) %>% dplyr::summarise(Mean=mean(Abundance), SD = sd(Abundance)) %>% knitr::kable()

```

```{r fig3c, fig.cap="Fig 3C: Differential abundance analysis highlighted Bacteroidales S24/7 and Lacnospiraceae as most differential abunant families.", fig.dim=c(3,3)}
annot_data <- res.filt_genus[unique(lacno_bact_relabs$OTU),] %>% 
              data.frame %>% 
              rownames_to_column('OTU') %>% 
              bind_cols(taxlab = c('Lachnospiraceae NK4A136','Bacteroidales S24-7'),  xmin = c('T2','T2'), timepoint = c('T3','T3'), y_position =  c(0.6,0.7)) %>%
              select(annotations = padj, taxlab, timepoint, xmin, y_position)

ggplot(data=lacno_bact_relabs, aes(x=timepoint, y=Abundance)) +
  stat_boxplot(aes(fill=timepoint), alpha=.8, width=0.5) +
  facet_wrap(~taxlab) +
  scale_fill_manual('Timepoint', values=cm_palette[c(2,3)]) + 
  geom_signif(data = annot_data,
              aes(annotations = signif(annotations,2), xmin=xmin, xmax=timepoint, y_position = y_position), manual = TRUE) +
  theme_cm() +
  theme(strip.text = element_text(size=11)) +
  xlab('Timepoint') +
  ylab('Relative abundance')+
  guides(fill=FALSE)
```

```{r, cache=TRUE}
not12 <- gg_topi %>%
  subset_samples(!(timepoint %in% c("T1", "T2")))

x<-not12 %>%
  ordinate(method = "MDS", distance =  phyloseq::distance(not12, "wunifrac"), weighted = TRUE) %>% plot_ordination(not12, ., justDF = TRUE)

centroids <- aggregate(cbind(Axis.1, Axis.2)~timepoint, x, mean)
centroids[1:4,c('X2','Y2')] <- centroids[-1,c(2:3)]
```

```{r fig3d, fig.cap="Fig 3D: Ordination centroids beta diversity all timepoints", fig.dim = c(5,3)}
ggplot(x, aes(Axis.1, Axis.2, color=timepoint)) +
  geom_point(size = 1.5, alpha=0.7) +
  geom_point(data=centroids, size = 4) + 
  geom_segment(aes(x=Axis.1, y=Axis.2, xend=X2, yend=Y2), 
               arrow = arrow(length = unit(0.1,'inches')),
               data=centroids, group="1") + 
  scale_color_manual(name = "Timepoint", values = cm_palette[-c(1,2)]) +
  theme_cm()
```

## Panel ?: Ordination beta diversity T3 vs T7
```{r fig3x, fig.dim = c(5, 3)}
metadata_2cat <- mappingfile[mappingfile$timepoint %in% c('T7','T3'),]
distwu_2cat <- phyloseq::distance(subset_samples(gg_topi, timepoint %in% c('T7','T3')), "wunifrac")
permanova <- vegan::adonis(formula = distwu_2cat ~ merge_timepoint, data = metadata_2cat)

subset(ordwu, timepoint %in% c('T7','T3')) %>%
ggplot(aes(Axis.1, Axis.2)) +
  geom_point(aes(color=timepoint), size=3, alpha=.8) +
  scale_color_manual(name = "Timepoint", values = cm_palette[c(3,7)])+
  theme_cm() +
  annotation_custom(grob = grid::textGrob(bquote(atop(italic("p-value")==.(permanova$aov.tab$`Pr(>F)`[1]),italic(R^2)==.(signif(permanova$aov.tab$R2[1], 2)))), gp=grid::gpar(col="black", fontsize=11)),  xmin = 0, xmax = 0, ymin = .1, ymax = .1)
```


```{r, cache=TRUE}
ggtopi_subs <-subset_samples(gg_topi, timepoint %in% c('T3','T7'))
ggtopi_subs.relab <- transform_sample_counts(ggtopi_subs, function(x) x/sum(x))
ggtopi_subs.genus <- tax_glom(ggtopi_subs,taxrank = "Genus")
ggtopi_subs.genus.relab <- transform_sample_counts(ggtopi_subs.genus, function(x) x/sum(x))

mmtx <- model.matrix(object = ~ timepoint + timepoint:real_vaccine + timepoint:real_bifido + timepoint:real_vaccine:real_bifido, data = data.frame(ggtopi_subs@sam_data))
idx <- which(apply(mmtx, 2, function(x) all(x==0)))
mmtx <- mmtx[,-idx]

pds_37 <- phyloseq_to_deseq2(ggtopi_subs, design = ~ timepoint + timepoint:real_vaccine + timepoint:real_bifido + timepoint:real_vaccine:real_bifido, ignoreRank = TRUE)
dds_37 <- DESeq2::DESeq(pds_37, parallel = TRUE, quiet = TRUE, full = mmtx)

pds_genus <- phyloseq_to_deseq2(ggtopi_subs.genus, design =  ~ timepoint + timepoint:real_vaccine + timepoint:real_bifido + timepoint:real_vaccine:real_bifido, ignoreRank = TRUE)
dds_genus <- DESeq2::DESeq(pds_genus, parallel = TRUE, quiet = TRUE, full = mmtx)
```

```{r, cache=TRUE}
res37 <- DESeq2::results(dds_genus, name = "timepointT7", alpha = 0.05)
res37.filt <- res37[!is.na(res37$padj),]
res37.filt <- res37.filt[res37.filt$padj<0.05,]

t37_samples_idx <- grep('T7|T3', sample_names(ggtopi_subs), perl = TRUE)

genus_ab_t <- otu_table(ggtopi_subs.genus.relab)[rownames(res37.filt), ] %>%
            data.frame %>%
            tibble::rownames_to_column("OTU") %>%
            tidyr::gather_("SampleID", "Abundance", setdiff(colnames(.), "OTU")) %>%
            mutate(timepoint=factor(stringr::str_sub(.$SampleID,12, 13)))

```

```{r fig4a, fig.cap="Fig 4A: Boxplot of abundance of significant genera from DESeq2 differential analysis. Genera with median below 1% are filtered", fig.dim = c(5,3)}
genus_ab_t %>%
  bind_cols(data.frame(tax_table(ggtopi_subs.genus.relab)[genus_ab_t$OTU,c('Phylum','Family','Genus')])) %>%
  filter(OTU %in% (genus_ab_t %>%
  group_by(OTU, timepoint) %>%
  summarise(median=median(Abundance)) %>%
  group_by(OTU) %>%
  summarise(filt=min(median)>0.01) %>% filter(filt==TRUE))$OTU) %>%
  filter(Phylum != "Unassigned") %>%
  mutate(taxlab = ifelse(stringr::str_detect(Genus,'uncultured'), paste('',Family,sep = ''), paste(Genus))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'Unknown'), paste('Unknown',Family,sep = ' '), paste(taxlab))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'Unknown Unknown'), paste('Unknown',Phylum,sep = ' '), paste(taxlab))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'Uncultured uncultured'), paste('Uncultured',Phylum,sep = ' '), paste(taxlab))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'group'), str_replace(taxlab, ' group',''), paste(taxlab))) %>%
ggplot() +
  geom_boxplot(aes(reorder(taxlab, Abundance, FUN = median), Abundance, fill=timepoint),  position = position_dodge(-.85),alpha=.8) +
  facet_grid(Phylum ~ ., scales = "free", space = "free_y", as.table= T) +
  scale_fill_manual(name = "Timepoint", values = cm_palette[c(3,7)]) +
  coord_flip() +
  xlab('') +
  ylab("Relative abundance") +
  theme_cm()
```

```{r supplfig4a, fig.cap="Supplemenrary Fig 4a: Boxplot of abundance of significant genera from DESeq2 differential analysis", fig.height=9}
genus_ab_t %>%
  bind_cols(data.frame(tax_table(ggtopi_subs.genus.relab)[genus_ab_t$OTU,c('Phylum','Family','Genus')])) %>%
  filter(Phylum != "Unassigned") %>%
  mutate(taxlab = ifelse(stringr::str_detect(Genus,'uncultured'), paste('Uncultured',Family,sep = ' '), paste(Genus))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'Unknown'), paste('Unknown',Family,sep = ' '), paste(taxlab))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'Unknown Unknown'), paste('Unknown',Phylum,sep = ' '), paste(taxlab))) %>%
  mutate(taxlab = ifelse(stringr::str_detect(taxlab,'Uncultured uncultured'), paste('Uncultured',Phylum,sep = ' '), paste(taxlab))) %>%
ggplot() +
  geom_boxplot(aes(reorder(taxlab, Abundance, FUN = median), Abundance, fill=timepoint),  position = position_dodge(-.85),alpha=.8) +
  facet_grid(Phylum ~ ., scales = "free", space = "free_y", as.table= T) +
  scale_fill_manual(name = "Timepoint", values = cm_palette[c(3,7)]) +
  coord_flip() +
  scale_y_log10() +
  xlab('') +
  ylab("Relative abundance") +
  theme_cm() +
  theme(strip.text.y = element_text(angle = 360),
        legend.position = "bottom")
```

```{r, cache=TRUE}
idx_247 <- which(tax_table(gg_topi.genus.relab)[,'Family'] == "Bacteroidales S24-7 group" & tax_table(gg_topi.genus.relab)[,'Genus'] == "uncultured bacterium")
idx_lachno <- which(tax_table(gg_topi.genus.relab)[,'Genus'] == "Lachnospiraceae NK4A136 group" )

k<- otu_table(gg_topi.genus.relab)[c(idx_247,idx_lachno),] %>%
   data.frame %>%
   tibble::rownames_to_column("OTU") %>%
   tidyr::gather_("SampleID", "Abundance", setdiff(colnames(.), "OTU")) %>%
   mutate(timepoint=stringr::str_sub(.$SampleID,12, 13)) %>%
   mutate(condition= stringr::str_sub(.$SampleID,4, 6)) %>%
   group_by(timepoint, condition, OTU) %>%
   summarise(Abundance = list(Abundance)) %>%
   spread(timepoint, Abundance) %>%
   bind_cols(data.frame(tax_table(gg_topi.genus.relab)[.$OTU,c('Family','Genus')])) %>%
   mutate(taxlab = str_replace(ifelse(stringr::str_detect(Genus,'uncultured'), paste(Family,sep = ''), paste(Genus, sep = '')), ' group','')) %>%
   select(-Family, -Genus)

abs_test <- data.frame() 
for(c in unique(k$condition)){
  for(o in unique(k$taxlab)){
    for(t in combn(colnames(k)[-c(1:2,10)], 2, simplify = FALSE)){
      l <-k %>%
        filter(condition == c & taxlab == o) %>%
        select(t)
      res <- t.test(unlist(l[,2]),unlist(l[,3]))
      abs_test %<>% bind_rows( data.frame( Condition = c,
                                           taxlab = o,
                                           Timepoint1 = t[1],
                                           Timepoint2 = t[2],
                                           p.value = signif(res$p.value,3),
                                           Direction = sign(diff(res$estimate))
                                         )
                             )
    }
  }
}
```

```{r}
knitr::kable(abs_test)
```

```{r fig4B, fig.cap="Fig 4B: Abundance of Bacteroidales 24/7 and Lachnospiraceae NK4A136 through timepoints and treatment", fig.dim=c(5,4)}
idx_247 <- which(tax_table(gg_topi.genus.relab)[,'Family'] == "Bacteroidales S24-7 group" & tax_table(gg_topi.genus.relab)[,'Genus'] == "uncultured bacterium")
idx_lachno <- which(tax_table(gg_topi.genus.relab)[,'Genus'] == "Lachnospiraceae NK4A136 group" )

annot_df <- abs_test %>%
  filter(Condition %in% c('VVB','VVP')) %>%
  filter(Timepoint2 == 'T6' & Timepoint1 %in% c('T4','T5')) %>%
  mutate(xmin = as.numeric(str_sub(Timepoint1, 2,2)) + ifelse(Condition == 'VVB', .094, .282),
         xmax = as.numeric(str_sub(Timepoint2, 2,2)) + ifelse(Condition == 'VVB', .094, .282),
                    #L4VVB,L5VVB,B4VVB,B5VVB,L4VVP,L5VVP,B4VVP,B5VVP
         y_position = c(.75,  #L4B
                        .45, #L5B
                        
                        .93,  #B4B
                        .73,  #B5B
                        
                        .65,  #L4P
                        .55,  #L5P
                        
                        .83, #B4P
                        .63) #B5P
         ,
         annotations = paste('p=',signif(p.value, 2), sep = '')) %>%
  select(taxlab, annotations, xmax, xmin, y_position)

otu_table(gg_topi.genus.relab)[c(idx_247,idx_lachno),] %>%
  data.frame %>%
  tibble::rownames_to_column("OTU") %>%
  tidyr::gather_("SampleID", "Abundance", setdiff(colnames(.), "OTU")) %>%
  mutate(timepoint=stringr::str_sub(.$SampleID,12, 13)) %>%
  mutate(condition= stringr::str_sub(.$SampleID,4, 6)) %>%
  bind_cols(data.frame(tax_table(gg_topi.genus.relab)[.$OTU,c('Phylum','Family','Genus')])) %>%
  mutate(taxlab = str_replace(ifelse(stringr::str_detect(Genus,'uncultured'), paste(Family,sep = ''), paste(Genus, sep = '')), ' group','')) %>%
ggplot() +
  geom_boxplot(aes(timepoint, Abundance, fill=condition), alpha=.8) +
  scale_fill_manual(name = "Treatment", values = c("#a6d854","#ffd92f","#66c2a5","#fc8d62")) +
  facet_wrap(facets = 'taxlab', nrow = 2, scales = "free_x") +
  geom_signif(data = annot_df, manual = TRUE, aes(xmin = xmin, xmax = xmax, annotations = annotations, y_position = y_position),textsize=3) +
  theme_cm() +
  theme(strip.text = element_text(family = "sans-serif", size = 9, colour = "black"),
        axis.text = element_text(family = "sans-serif", size = 8, colour = "black"),
        axis.title = element_text(family = "sans-serif", size = 8, colour = "black"))+
  ylab('Relative abundance') +
  xlab('Timepoint')
```

```{r, cache=TRUE}
brayc_ds <- distancesbc %>% 
  dplyr::filter(topo1==topo2) %>%
  dplyr::filter(timepoint1==3) %>%
  dplyr::filter(timepoint2>4) %>%
  dplyr::select(cols, timepoint2, value) %>%
  dplyr::left_join(mappingfile, by=c('cols' = 'Description'))

ds_corr_braycf <- data.frame()
for(x in unique(brayc_ds$timepoint2)){
  # for(y in levels(brayc_ds$condizione)){
    tmp_res <- with(brayc_ds %>% filter(timepoint2==x), cor.test(value, tumor_mass))
    ds_corr_braycf %<>% bind_rows(data.frame(timepoint = paste('T', x, '-T3',sep = ''), corr = signif(tmp_res$estimate,2), pval = signif(tmp_res$p.value,2), label = paste('p=',signif(tmp_res$p.value,2),'\nr=', signif(tmp_res$estimate,2), sep = '')))
}
ds_corr_braycf[,c('x','y')] <- list(c(.45,.45,.45),c(300,670,2000))
```

```{r fig4C, fig.cap="Fig 4C: Scatterplot of tumor size and difference of beta diversity ", fig.dim=c(5,2)}
distancesbc %>% 
  dplyr::filter(topo1==topo2) %>%
  dplyr::filter(timepoint1==3) %>%
  dplyr::filter(timepoint2>4) %>%
  dplyr::select(cols, timepoint2, value) %>%
  dplyr::left_join(mappingfile, by=c('cols' = 'Description')) %>%
  mutate(timepoint = paste('T',timepoint2,'-T3',sep = '')) %>%
ggplot(aes(value,tumor_mass)) +
  geom_point(size=2) +
  facet_wrap(facets = 'timepoint', nrow = 1, shrink = TRUE, scales = 'free_y') +
  geom_line(stat='smooth', method = 'lm', color='red', alpha=0.7, size=.7) + 
  ylab('Tumor mass (mm3)') +
  xlab('Bray Curtis distance') +
  geom_text(data = ds_corr_braycf, aes(x=x,y=y, label=label), size=2) +
  theme_cm() +
  theme(strip.text = element_text(family = "sans-serif", size = 9, colour = "black"),
        axis.text = element_text(family = "sans-serif", size = 8, colour = "black"),
        axis.title = element_text(family = "sans-serif", size = 8, colour = "black"))
```


```{r}
tbl_data <- otu_table(gg_topi.genus.relab)[idx_247,] %>%
  data.frame %>%
  tidyr::gather_("SampleID", "Abundance", colnames(.)) %>%
  mutate(mouseid=stringr::str_sub(.$SampleID,8, 10)) %>%
  mutate(timepoint=stringr::str_sub(.$SampleID,12, 13)) %>%
  mutate(condition= stringr::str_sub(.$SampleID,4, 6)) %>%
  filter(timepoint %in% c('T3','T7')) %>%
  select(-SampleID) %>%
  spread(timepoint,Abundance) %>%
  mutate(diff_abb = T3-T7) %>%
  arrange(mouseid) %>%
  bind_cols( gg_topi.genus.relab %>%
              sample_data %>%
              filter(timepoint == 'T7') %>%
              select(id.topo, tumor_mass) %>%
              arrange(id.topo) %>%
              select(-id.topo))
```
```{r fig4D, fig.cap="Fig 4D: Scatterplot of tumor size and difference of beta diversity ", fig.dim=c(3.5,3.5)}
tbl_data %>%
ggplot(aes(diff_abb, tumor_mass)) +
  geom_point(size=2) +
  facet_wrap(facets = 'condition', nrow = 2, scales = 'free') +
  geom_line(stat='smooth', method = 'lm', color='red', alpha=0.7, size=.7) + 
  theme_cm() +
  theme(strip.text = element_text(family = "sans-serif", size = 9, colour = "black"),
        axis.text = element_text(family = "sans-serif", size = 8, colour = "black"),
        axis.title = element_text(family = "sans-serif", size = 8, colour = "black")) +
  xlab('Relative abundance (T3-T7)') +
  ylab('Tumor mass (mm3)')
```

```{r, cache=TRUE}
tbl_data %>%
  select(-T3,-T7, -mouseid) %>%
  group_by(condition) %>%
  summarise(diff_abb = list(diff_abb), tumor_mass = list(tumor_mass)) %>%
  group_by(condition) %>%
  mutate(cor.test = paste(unlist(cor.test(unlist(diff_abb), unlist(tumor_mass))[c('p.value','estimate')]), collapse = ' ')) %>%
  separate(cor.test, into = c('p.value','estimate'), sep = ' ')
```

